### ISSUE TITLE
Use of USB file system rather than separate SD card interface?

### ISSUE THREAD

**Issue by marvbloke** [guidol70/RunCPM_RPi_Pico#2]
Do you think it would be possible to use the Pico/Tiny2040’s USB drive capabilities rather than requiring a separate SD card interface? This would lower the barrier to entry and make it even easier to get started with CP/M on the RP2040 platform by just dragging files onto it from a computer

**Comment by guidol70** [comment]
I only know the possibility to flash the program via a .UF2 binary to the Pico.
I didnt know how to use the 2MB (also not much for CP/M programms).
In the past I remember that there was a like emulator which has 2 .UF2 - one for the program ans one for a filesystem. But cant remember the name. I thought it is kevin Boone's CP/M-Emulator fo the Pico, but there I do only found a X-/Y-Modem Transfer in the filesystem.
Maybe it was a Forth-Interpreter for the Pico with this feature?

The SDCard Interface is connected oly on some lines/wires and support much more Filesystem-Space and its easy to transfer files, because you can simply copy from your computer to the SDcard.

The other "problem" is, that RunCPM is based on SdFat-Library calls to the filesystem and all of them have to be converted to local filesystem.

**Comment by guidol70** [comment]
@marvbloke maybe a ready-made Pico board with SD-Slot is somehting for you?
The Invector Challenger SD/RTC has been reported to be able to run RunCPM - so no soldering for you ;)
at https://www.tindie.com/products/invector/challenger-rp2040-sdrtc/

![Invector_Challenger_SDRTC](https://user-images.githubusercontent.com/5121124/202656749-a0d9c724-7553-4fd4-9c2d-d295a4673d3c.jpg)

**Comment by marvbloke** [comment]
Thanks for that Guido. The reason I was asking was to try and keep the size right down - as small as possible. A Tiny2040 on its own would DEFINITELY be the smallest possible CP/M machine!
